### ISSUE TITLE
need update to 7.1.1 for free security with ssl

### ISSUE THREAD

**Issue by zqc0512** [TrumanDu/indices_view#10]
it know 7.1.1 basic secuirty is free know 
need security  support.

**Comment by TrumanDu** [comment]
ack

**Comment by TrumanDu** [comment]
wait to release,

**Comment by TrumanDu** [comment]
[see here](https://github.com/TrumanDu/indices_view/releases/download/v7.1.1/indices_view-7.1.1.zip)
