### ISSUE TITLE
can output the plugin .zip file to download?

### ISSUE THREAD

**Issue by zqc0512** [TrumanDu/indices_view#4]
can output the plugin .zip file to download?
with my network can't connect to internet.
i need the kibana plugin .zip file as 
./kibana-plugin install file:///indices_view.zip  to install.
@TrumanDu

**Comment by zqc0512** [comment]
你在说明中添加下吧。没有看到下载的地方……

**Comment by zqc0512** [comment]
修改这个文件
{
  "name": "indices_view",
  "version": "5.5.1",
  "description": "An awesome kibana plugin for view indies!",
  "main": "index.js",
  "kibana": {
    "version": "5.5.1",
    "templateVersion": "7.2.3"
  },
  "dependencies": {
    "angular-ui-bootstrap": "^2.5.6",
    "elasticsearch": "^14.1.0"
  },
  "build": {
    "git": {
      "count": "5",
      "sha": "527c775",
      "date": "Fri, 9 Feb 2018 15:57:50 +0800"
    },
    "date": "Fri Feb 09 2018 16:14:26 GMT+0800 (China Standard Time)"
  }
}

version 修改成5.6.8 是否支持？
@TrumanDu

**Comment by TrumanDu** [comment]
@zqc0512 理论上支持，我本地没这个环境，你可以测试一下。有问题再反馈，你可以把我们的源码下载下来，修改该version,执行`npm run build`,或者直接将该文件夹复制到kibana的plugins目录下,

**Comment by zqc0512** [comment]
可以了。修改了版本能够用。用用看有问题没有。
主要是内网环境 npm不怎么好使……
@TrumanDu

**Comment by TrumanDu** [comment]
这个不需要额外依赖，什么公司？？
@zqc0512

**Comment by zqc0512** [comment]
加微信说吧。13581722147
@TrumanDu

**Comment by zqc0512** [comment]
呵呵，本地没有node环境的。没有npm命令的。这个是kibana自带的。编译不了的。

**Comment by TrumanDu** [comment]
ok,有问题再重新提个吧。
