### ISSUE TITLE
the indices view can add function to summing daily data ?

### ISSUE THREAD

**Issue by zqc0512** [TrumanDu/indices_view#6]
summing yestoday all date or like 20180801-20180807 date to Summing.
now only base on indices name not date.
thanks.
@TrumanDu

**Comment by TrumanDu** [comment]
@zqc0512 
![20180816104819](https://user-images.githubusercontent.com/16727775/44184484-eadb8000-a141-11e8-9cae-5439a27c9d71.png)
)

**Comment by zqc0512** [comment]
yes but when merge can't summing  total data as one day.
it one index by index .
![image](https://user-images.githubusercontent.com/25192261/44184772-275bab80-a143-11e8-8741-38f73ac963e4.png)

@TrumanDu

**Comment by TrumanDu** [comment]
this plugin just can merge prefix name index. such as : metricbeat-6.3.0-2018.08.08/metricbeat-6.3.0-2018.08.09 merge for metricbeat-6.3.0-*(2)
--
