### ISSUE TITLE
请教下我在kibana6.4.2版本下开发的插件，怎么配置代理去请求es中的数据啊，在es中已经都有数据了

### ISSUE THREAD

**Issue by wxxyanmei** [TrumanDu/indices_view#8]

**Comment by TrumanDu** [comment]
请查看[地址](https://kibana.gitbook.io/kibana-plugin-development-tutorial/gao-ji-jin-jie/huo-qu-elasticsearch-tong-xin-api)，原始文档详见[地址](https://github.com/TrumanDu/kibana-plugin-development-tutorial)，如果方便的话，请给予star,thanks.
